First alpha version of the library
glpi-project/java-library-glpi pull request #16
Opened 2017-10-24 21:41 UTC by rafaelje

## Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Conventional Commit](https://conventionalcommits.org/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

## What is the new behavior?

This is the first alpha version of the library with:
- initial documentation
- initial instrumented test
- Java Example
- CI
- initsession()
- killsession()
- getMyProfiles()
- getActiveProfile()
- changeActiveProfile()
- lostPassword()
- recoveryPassword()
- getMyEntities()
- getActiveEntities()
- changeActiveEntities()
- getFullSession()
- getAnItem()
- getAllItems()
- getSubItems()
- addItems()
- updateItems()
- deleteItems()

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2017-10-25 14:02 UTC, ajsb85 approved these changes
Reviewed

2017-10-25 14:56 UTC, rafaelje commented
@rafaelje @ajsb85 When you can Please help me to review this PR

2017-10-25 18:54 UTC, ajsb85 requested changes

2017-10-25 18:54 UTC, ajsb85 commented on glpi/src/main/java/org/flyve/glpi/query/GetSubItemQuery.java
> +package org.flyve.glpi.query;
Why org.flyve.glpi?

The package id is: org.glpi.api

2017-10-25 18:54 UTC, ajsb85 commented
This branch cannot be rebased due to conflicts

2017-10-25 20:06 UTC, ajsb85 approved these changes
Reviewed

2017-10-26 09:27 UTC, ajsb85 approved these changes
Reviewed

2017-10-26 09:27 UTC, ajsb85 commented
Hi, @rafaelje 

Could you rebase your branch to resolve the conflicts in the PR?

Thanks.

2017-10-26 13:01 UTC, ajsb85 commented
Hi, @rafaelje This branch cannot be rebased due to conflicts

I can see the changes to update in your branch here:

https://github.com/rafaelje/java-library-glpi/compare/develop...glpi-project:develop?expand=1

2017-10-26 13:03 UTC, rafaelje commented
Hi @ajsb85 you are trying to compare develop branch with develop but is feature/api with develop

2017-10-26 13:20 UTC, closed without merging