Handle multiple request to download files
glpi-project/java-library-glpi pull request #59
Opened 2018-12-04 20:48 UTC by Ivans51

Signed-off-by: Ivan Del Pino <idelpino@teclib.com>

### Changes description

Add method to handle multiple download file 

### Checklist

Please check if your PR fulfills the following specifications:

- [x] Tests for the changes have been added
- [ ] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@ivans51 |4|

### References

Closes: https://github.com/glpi-project/java-library-glpi/issues/58

2018-12-07 20:29 UTC, ajsb85 submitted a review, later dismissed

2018-12-07 21:28 UTC, rafaelje reviewed
We need a limit if I send 20 urls should have a limit like 3 at same time

2018-12-13 18:54 UTC, ajsb85 requested changes
This branch has conflicts that must be resolved

2018-12-14 21:36 UTC, ajsb85 approved these changes

2018-12-14 22:13 UTC, ajsb85 approved these changes

2018-12-14 22:13 UTC, merged